x-environment: &default-environment
  PUBLIC_REQUEST_SCHEME: http
  INTERNAL_DOMAIN_NAME: kobo.local
  PUBLIC_DOMAIN_NAME: kobo.local
  KOBOCAT_URL: http://kc.kobo.local
  KOBOCAT_INTERNAL_URL: http://kobocat:8000
  KOBOFORM_PUBLIC_SUBDOMAIN: kf
  KOBOCAT_PUBLIC_SUBDOMAIN: kc
  ENKETO_REDIS_MAIN_URL: redis://redis:6379
services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - kobo-be-network
  mongo:
    image: mongo
    networks:
      - kobo-be-network
  redis:
    image: redis
    networks:
      - kobo-be-network
  kpi: &django
    image: kobotoolbox/kpi:2.024.33c
    environment:
      <<: *default-environment
      DJANGO_DEBUG: "true" # Remove?
      USE_X_FORWARDED_HOST: "true"
      PYTHONUNBUFFERED: 1  # Move to Dockerfile?
      DATABASE_URL: postgis://postgres:postgres@postgres:5432/postgres
      KC_DATABASE_URL: postgis://postgres:postgres@postgres:5432/kobocat
      SESSION_COOKIE_DOMAIN: .kobo.local
      REDIS_SESSION_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379
      CACHE_URL: redis://redis:6379
      SERVICE_ACCOUNT_BACKEND_URL: redis://redis:6379
      ENKETO_URL: http://ee.kobo.local
    command: ./manage.py runserver 0:8000
    volumes:
      - ./.vols/static/kpi:/srv/src/kpi/staticfiles
    networks:
      kobo-fe-network:
        aliases:
          - kobocat
      kobo-be-network: {}
  worker:
    <<: *django
    command: celery -A kobo worker -l info -s /tmp/celerybeat-schedule --pool threads -Q kpi_low_priority_queue,kpi_queue,kobocat_queue
  nginx:
    image: nginx
    environment:
      <<: *default-environment
      TEMPLATED_VAR_REFS: "$${PUBLIC_REQUEST_SCHEME} $${INTERNAL_DOMAIN_NAME} $${PUBLIC_DOMAIN_NAME} $${KOBOFORM_PUBLIC_SUBDOMAIN} $${KOBOCAT_PUBLIC_SUBDOMAIN} $${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}"
    networks:
      kobo-fe-network:
        aliases:
          - kf.kobo.local
          - kc.kobo.local
          - ee.kobo.local
    ports:
      - 80:80
    volumes:
        - ./.vols/static:/srv/www:ro
        - ./.vols/kobocat_media_uploads:/media
        - ./.vols/kpi_media/__public:/srv/kpi_media/__public:ro
        - ./nginx/docker-entrypoint.d/30-init-kobo-nginx.sh:/docker-entrypoint.d/30-init-kobo-nginx.sh
        - ./nginx/kobo-docker-scripts/:/kobo-docker-scripts
  enketo_express:
    image: kobotoolbox/enketo-express-extra-widgets:6.2.2
    init: true
    environment:
      <<: *default-environment
      ENKETO_REDIS_CACHE_URL: "redis://redis:6379"
      ENKETO_MAX_PROCESSES: 1
      ENKETO_LINKED_FORM_AND_DATA_SERVER_SERVER_URL: ""
      ENKETO_LINKED_FORM_AND_DATA_SERVER_AUTHENTICATION_ALLOW_INSECURE_TRANSPORT: "true"
    command: node app.js
    networks:
      - kobo-fe-network
      - kobo-be-network

networks:
  kobo-fe-network:
    driver: bridge
  kobo-be-network:
    driver: bridge
