# copyleft 2015 teodorescu.serban@gmail.com
PSQL_ADMIN=${PSQL_ADMIN}
KOBO_PSQL_DB_NAME=${KOBO_PSQL_DB_NAME}
KOBO_PSQL_DB_USER=${KOBO_PSQL_DB_USER}
KOBO_PSQL_DB_PASS=${KOBO_PSQL_DB_PASS}
PSQL_HOST=${PSQL_HOST}
PSQL_PORT=${PSQL_PORT}
