
# =======
AWS_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
AWS_SES_REGION_ENDPOINT=${AWS_SES_REGION_ENDPOINT}
AWS_SES_REGION_NAME=${AWS_SES_REGION_NAME}
DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
DKOBO_PREFIX=${DKOBO_PREFIX}
EMAIL_BACKEND=${EMAIL_BACKEND}
ENKETO_PREVIEW_URI=${ENKETO_PREVIEW_URI}
ENKETO_SERVER=${ENKETO_SERVER}
KOBOCAT_INTERNAL_URL=${KOBOCAT_INTERNAL_URL}
KOBOCAT_URL=${KOBOCAT_URL}
KOBO_SURVEY_PREVIEW_EXPIRATION=${KOBO_SURVEY_PREVIEW_EXPIRATION}
KOBO_USE_MINIFIED_SCRIPTS=${KOBO_USE_MINIFIED_SCRIPTS}
KPI_BROKER_URL=${KPI_BROKER_URL}
KPI_PREFIX=${KPI_PREFIX}

# =======
# Remove "KPI_" prefix from variables.
DJANGO_DEBUG=${KPI_DJANGO_DEBUG}
LIVERELOAD_SCRIPT=${KPI_LIVERELOAD_SCRIPT}
RAVEN_DSN=${KPI_RAVEN_DSN}
