#!/bin/sh -e

# FIXME: Remove pending upgrade to RabbitMQ 3.4+.
# Apparently zealously watching pre-3.4 RabbitMQ's startup causes it to get 
#   nervous and fail, so try waiting arbitrarily? See:
#   https://groups.google.com/d/msg/rabbitmq-users/hJme_Fgo2VQ/kLVFfgsySrgJ
sleep 10

echo 'Waiting for RabbitMQ to become available...'
while ! rabbitmqctl list_vhosts > /dev/null 2>&1
do
    sleep 2
done
echo 'The RabbitMQ service is up!'

# KoBoCat uses the default RabbitMQ user, but it's necessary to create a
# separate user and vhost for KPI
if rabbitmqctl list_vhosts | grep kpi > /dev/null
then
    echo 'RabbitMQ already configured for KPI.'
else
    rabbitmqctl add_user kpi kpi || true
    rabbitmqctl add_vhost kpi || true
    rabbitmqctl set_permissions -p kpi kpi '.*' '.*' '.*'
fi

# Don't run forever
sv stop rabbit-configure > /dev/null
