# KoBoCAT environment.
export KOBOFORM_URL="http://${HOST_ADDRESS}:${KOBOFORM_PUBLIC_PORT}"
#KOBOCAT_MEDIA_URL="http://${HOST_ADDRESS}:${KOBOCAT_PUBLIC_PORT}/media/"
export ENKETO_URL="http://${HOST_ADDRESS}:${ENKETO_EXPRESS_PUBLIC_PORT}"
export CSRF_COOKIE_DOMAIN="${HOST_ADDRESS}"
export DJANGO_ALLOWED_HOSTS="${HOST_ADDRESS}" # Necessary?

# dkobo.
export KOBOFORM_PREVIEW_SERVER=${KOBOFORM_URL}
export KOBOCAT_URL=http://${HOST_ADDRESS}:${KOBOCAT_PUBLIC_PORT}
export ENKETO_URL=http://${HOST_ADDRESS}:${ENKETO_EXPRESS_PUBLIC_PORT} # Duplicate.
export CSRF_COOKIE_DOMAIN="${CSRF_COOKIE_DOMAIN}" # Duplicate.
export DJANGO_ALLOWED_HOSTS="${HOST_ADDRESS}" # Duplicate. Necessary?

# KPI.
export ENKETO_URL="http://${HOST_ADDRESS}:${ENKETO_EXPRESS_PUBLIC_PORT}" # Duplicate.
export KOBOCAT_URL="http://${HOST_ADDRESS}:${KOBOCAT_PUBLIC_PORT}" # Duplicate.
export CSRF_COOKIE_DOMAIN="${CSRF_COOKIE_DOMAIN}" # Duplicate.
export DJANGO_ALLOWED_HOSTS="${HOST_ADDRESS}" # Duplicate. Necessary?
