# KoBoCAT environment.
export KOBOFORM_URL="http://${HOST_ADDRESS}:${KPI_PUBLIC_PORT}"
#KOBOCAT_MEDIA_URL="http://${HOST_ADDRESS}:${KOBOCAT_PUBLIC_PORT}/media/"
export ENKETO_URL="http://${HOST_ADDRESS}:${ENKETO_EXPRESS_PUBLIC_PORT}"
export CSRF_COOKIE_DOMAIN="${HOST_ADDRESS}"
export DJANGO_ALLOWED_HOSTS="${HOST_ADDRESS}"

# KPI.
export ENKETO_URL="http://${HOST_ADDRESS}:${ENKETO_EXPRESS_PUBLIC_PORT}" # Duplicate.
export KOBOCAT_URL="http://${HOST_ADDRESS}:${KOBOCAT_PUBLIC_PORT}"
export KOBOCAT_INTERNAL_URL="${KOBOCAT_URL}" # FIXME: Use an actual internal URL.
export CSRF_COOKIE_DOMAIN="${HOST_ADDRESS}" # Duplicate.
export DJANGO_ALLOWED_HOSTS="${HOST_ADDRESS}" # Duplicate.

# Enketo Express.
export ENKETO_API_KEY="${ENKETO_API_TOKEN}"
