# KoBoCAT environment.
export KOBOFORM_URL="https://${KOBOFORM_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}"
#KOBOCAT_MEDIA_URL="https://${KOBOCAT_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}/media/"
export ENKETO_URL="https://${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}"
export CSRF_COOKIE_DOMAIN=".${PUBLIC_DOMAIN_NAME}"
export DJANGO_ALLOWED_HOSTS=".${PUBLIC_DOMAIN_NAME}" # Necessary?

# dkobo.
export KOBOFORM_PREVIEW_SERVER="https://${KOBOFORM_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}"
export KOBOCAT_URL="https://${KOBOCAT_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}"
export ENKETO_URL="https://${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}" # Duplicate.
export CSRF_COOKIE_DOMAIN=".${PUBLIC_DOMAIN_NAME}" # Duplicate.
export DJANGO_ALLOWED_HOSTS=".${PUBLIC_DOMAIN_NAME}" # Duplicate. Necessary?

# KPI.
export ENKETO_URL="https://${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}" # Duplicate.
export KOBOCAT_URL="https://${KOBOCAT_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}" # Duplicate.
export CSRF_COOKIE_DOMAIN=".${PUBLIC_DOMAIN_NAME}" # Duplicate.
export DJANGO_ALLOWED_HOSTS=".${PUBLIC_DOMAIN_NAME}" # Duplicate. Necessary?
